/**
 * Generates one App Router `page.tsx` per navigable dashboard route, mirroring
 * the structure declared in `src/config/navigation.ts`. Run after editing the
 * navigation config:
 *
 *     npm run gen:routes
 *
 * Generated pages are thin re-exports of `DashboardSectionPage` and carry a
 * `@generated` marker; this script also removes generated pages (and the empty
 * directories left behind) whose route no longer exists in the config. Files
 * without the marker — including `dashboard/layout.tsx` and `dashboard/page.tsx`
 * — are never touched.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { dashboardRoutes } from "../src/config/navigation.ts"

const MARKER = "@generated by scripts/generate-dashboard-routes.ts"
const PAGE_SOURCE = `// ${MARKER} — do not edit; run \`npm run gen:routes\`.
export { default } from "@/components/dashboard/dashboard-section-page"
`

const scriptDir = dirname(fileURLToPath(import.meta.url))
const appDir = join(scriptDir, "..", "src", "app")
const dashboardDir = join(appDir, "dashboard")

const targets = new Set(
  dashboardRoutes.map((route) =>
    join(appDir, ...route.url.split("/").filter(Boolean), "page.tsx"),
  ),
)

let written = 0
for (const file of targets) {
  mkdirSync(dirname(file), { recursive: true })
  if (!existsSync(file) || readFileSync(file, "utf8") !== PAGE_SOURCE) {
    writeFileSync(file, PAGE_SOURCE)
    written++
  }
}

let removed = 0
function prune(dir: string): void {
  if (!existsSync(dir)) return
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      prune(full)
      if (readdirSync(full).length === 0) rmSync(full, { recursive: true })
    } else if (
      entry === "page.tsx" &&
      !targets.has(full) &&
      readFileSync(full, "utf8").includes(MARKER)
    ) {
      rmSync(full)
      removed++
    }
  }
}
prune(dashboardDir)

console.log(
  `dashboard routes: ${targets.size} pages (${written} written, ${removed} removed).`,
)
